### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sternschnaube** [mim1q/ConvenientNameTags#12]
Hello, is it possible to deactivate every feature?
I would love to make just a use of the rename function 😊
And please 1.19.3 support - if not already supported. Thanks.

**Comment by mim1q** [comment]
Hi, for now you can use the 0.2.1 version of the mod, which only has the renaming feature added. I will consider porting to 1.19.3, thank you for the suggestion :)

**Comment by venaminecraft** [comment]
Thank you. I was testing the mod right now, everything loads fine on the server.
But I am not able to open the rename interface with right click. Needs to be updated.

**Comment by mim1q** [comment]
Can you open the interface using the newest release? Also, make sure you have the same version on the client and the server!

**Comment by venaminecraft** [comment]
I was missing the mod on client side, sorry. I was trying it right now (still with the old build).
Getting this error here, while I tried to perform the right click:

java.lang.NoClassDefFoundError: net/minecraft/class_4185$class_5316
	at Not Enough Crashes deobfuscated stack trace.(1.19.3+build.4)
	at net.minecraft.item.NameTagItem.use(NameTagItem:526)
	at net.minecraft.item.ItemStack.use(ItemStack:284)
	at net.minecraft.client.network.ClientPlayerInteractionManager.method_41929(ClientPlayerInteractionManager:391)
	at net.minecraft.client.network.ClientPlayerInteractionManager.sendSequencedPacket(ClientPlayerInteractionManager:278)
	at net.minecraft.client.network.ClientPlayerInteractionManager.interactItem(ClientPlayerInteractionManager:383)
	at net.minecraft.client.MinecraftClient.doItemUse(MinecraftClient:1802)
	at net.minecraft.client.MinecraftClient.handleInputEvents(MinecraftClient:2036)
	at net.minecraft.client.MinecraftClient.redirect$fal000$onTickRedirectHandleInputEvents(MinecraftClient:24612)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1863)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1150)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:781)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_4185$class_5316
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more

**Comment by mim1q** [comment]
Ah, it probably crashes because of 1.19.3 changes. I'll update the mod with a config file and make sure it works with that version, can't promise when tho

**Comment by venaminecraft** [comment]
Sounds great, please don't rush it 🥳
I will keep my eye on it.

**Comment by mim1q** [comment]
@sternschnaube 
Sorry for bothering, but I have updated the mod! Just letting you know 😄 
There's a new config file that lets you configure or disable some parts of the mod.
I haven't made it compatible with 1.19.3 unfortunately, but both 1.19.2 and 1.19.4 should work.

**Comment by venaminecraft** [comment]
Thanks alot. 1.19.4 is perfect, and later 1.20 when it's out 😊
